### ISSUE TITLE
Optional blocks / nilable procs?

### ISSUE THREAD

**Issue by connorshea** [ruby/ruby-signature#214]
In a lot of Ruby code, you can use a method either with or without a block. For example, with `create_table` in Rails' ActiveRecord:

```ruby
# With block
create_table(:suppliers) do |t|
  t.string :name
end

# Without block
create_table(:suppliers)
```

In Sorbet, the signature for this methods looks like this (simplified to remove a bunch of unnecessary stuff):

```ruby
sig do
  params(
    table_name: T.any(String, Symbol),
    blk: T.nilable(T.proc.params(t: ActiveRecord::ConnectionAdapters::TableDefinition).void)
  ).void
end
def create_table(table_name, &blk); end
```

But when I run `bundle exec rbs prototype rbi foo.rbi` on a file with a nilable proc, I get this error:

```
Unexpected block type: ^(ActiveRecord::ConnectionAdapters::TableDefinition t) -> void?
(SCOPE@9:2-9:41
 tbl: [:table_name, :blk]
 args:
   (ARGS@9:19-9:35
    pre_num: 1
    pre_init: nil
    opt: nil
    first_post: nil
    post_num: 0
    post_init: nil
    rest: nil
    kw: nil
    kwrest: nil
    block: :blk)
 body: nil)
```

So, how are we supposed to represent optional blocks in rbs files?
