### ISSUE TITLE
Blocks set to T.untyped aren't converted properly

### ISSUE THREAD

**Issue by connorshea** [ruby/ruby-signature#215]
Given a Sorbet `foo.rbi` with a single method:

```ruby
# typed: true
module Foo
  sig { params(blk: T.untyped).void }
  def bar(&blk); end
end
```

It returns this when I run `bundle exec rbs prototype rbi foo.rbi`:

```
Unexpected block type: untyped
(SCOPE@4:2-4:20
 tbl: [:blk]
 args:
   (ARGS@4:10-4:14
    pre_num: 0
    pre_init: nil
    opt: nil
    first_post: nil
    post_num: 0
    post_init: nil
    rest: nil
    kw: nil
    kwrest: nil
    block: :blk)
 body: nil)
# typed: true
module Foo
  def bar: () { () -> untyped } -> void
end
```

It should handle a block type set to `T.untyped` without erroring.

`def bar: () { () -> untyped } -> void` is the correct method signature, so it kind of already handles it correctly.

Please tell me if these kinds of issues shouldn't be opened yet while ruby-signature is still in development, I just figured I should report it :)
